version: "3.9"
services:
  backend:
    container_name: "easy-enrollment"
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=mongodb://mongodb:27017/easy-enrollment
    depends_on:
      - mongo_db

  mongo_db:
    container_name: "mongodb"
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
